# 1. 이름을 정해줍니다.
name: Deploy to EC2 (No Docker)

# 2. 이 스크립트를 언제 동작시킬 건지 정해줍니다.
on:
  # local 작업 내용이 main에 push가 되면 아래 스크립트를 동작하겠습니다.
  push:
    branches: [main]

jobs:
  deploy:
    # 3. github 측에서 준비한 ubuntu resource를 활용할 겁니다.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          # 4. 들어갈 때, 필요한 EC2 관련 보안정보들을 전달해줍니다.
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 경로 이동
            cd ~/mlops-project/Github/loan-api-server

            echo "===== Pull latest code ====="
            git pull origin main

            echo "===== Activate conda environment ====="
            source ~/miniconda3/etc/profile.d/conda.sh
            conda activate mlops

            echo "===== Install requirements ====="
            pip install --no-cache-dir -r requirements.txt

            echo "===== Restart systemd service ====="
            sudo systemctl daemon-reload
            sudo systemctl restart loan-api
            sudo systemctl status loan-api --no-pager
